"""
Tests de indexación incremental de runbooks.

Antes, init_runbooks_qdrant() salía temprano con `count > 0`, así que un runbook
nuevo añadido al repo nunca llegaba a Qdrant: la colección ya tenía documentos
desde el primer arranque. Los playbooks escritos después del despliegue inicial
eran invisibles para el agente.
"""
from __future__ import annotations

import os
from types import SimpleNamespace

import pytest


class _FakeQdrant:
    """Cliente Qdrant mínimo: registra lo que se sube."""

    def __init__(self, indexed: list[dict], collection="sre_runbooks"):
        self._indexed = indexed
        self._collection = collection
        self.upserted: list = []

    def get_collections(self):
        return SimpleNamespace(collections=[SimpleNamespace(name=self._collection)])

    def count(self, collection_name):
        return SimpleNamespace(count=len(self._indexed))

    def scroll(self, collection_name, limit, offset, with_payload, with_vectors):
        pts = [SimpleNamespace(payload=p) for p in self._indexed]
        return pts, None

    def upsert(self, collection_name, points):
        self.upserted.extend(points)


@pytest.fixture
def runbooks_dir(tmp_path):
    d = tmp_path / "runbooks"
    d.mkdir()
    for name in ("crash_loop.md", "oom_killed.md", "job_pod_failed.md"):
        (d / name).write_text(f"# {name}\ncontenido de prueba")
    return str(d)


def _patch_env(monkeypatch, client, runbooks_dir):
    from agents.sre import agent as sre_agent

    monkeypatch.setattr(sre_agent, "_RUNBOOKS_DIR", runbooks_dir, raising=False)

    import qdrant_client
    monkeypatch.setattr(qdrant_client, "QdrantClient", lambda **_kw: client)

    class _Resp:
        @staticmethod
        def json():
            return {"embedding": [0.1] * 768}

    import requests
    monkeypatch.setattr(requests, "post", lambda *_a, **_kw: _Resp())
    return sre_agent


def test_indexes_only_missing_runbooks(monkeypatch, runbooks_dir):
    """Los dos ya indexados se respetan; solo sube el nuevo."""
    client = _FakeQdrant([
        {"source": "crash_loop.md", "auto_generated": False},
        {"source": "oom_killed.md", "auto_generated": False},
    ])
    sre_agent = _patch_env(monkeypatch, client, runbooks_dir)

    sre_agent.init_runbooks_qdrant()

    subidos = {p.payload["source"] for p in client.upserted}
    assert subidos == {"job_pod_failed.md"}


def test_nonempty_collection_no_longer_skips_everything(monkeypatch, runbooks_dir):
    """La regresión original: colección con datos → no indexaba nada nuevo."""
    client = _FakeQdrant([{"source": "otro.md", "auto_generated": False}])
    sre_agent = _patch_env(monkeypatch, client, runbooks_dir)

    sre_agent.init_runbooks_qdrant()

    assert len(client.upserted) == 3, "debe subir los 3 runbooks del directorio"


def test_autogenerated_docs_do_not_mask_static_runbooks(monkeypatch, runbooks_dir):
    """Un runbook auto-generado con el mismo nombre no cuenta como indexado."""
    client = _FakeQdrant([
        {"source": "crash_loop.md", "auto_generated": True},
    ])
    sre_agent = _patch_env(monkeypatch, client, runbooks_dir)

    sre_agent.init_runbooks_qdrant()

    subidos = {p.payload["source"] for p in client.upserted}
    assert "crash_loop.md" in subidos


def test_all_indexed_uploads_nothing(monkeypatch, runbooks_dir):
    client = _FakeQdrant([
        {"source": n, "auto_generated": False}
        for n in ("crash_loop.md", "oom_killed.md", "job_pod_failed.md")
    ])
    sre_agent = _patch_env(monkeypatch, client, runbooks_dir)

    sre_agent.init_runbooks_qdrant()

    assert client.upserted == []


def test_scroll_failure_does_not_duplicate(monkeypatch, runbooks_dir):
    """Sin inventario fiable, mejor omitir que duplicar."""
    client = _FakeQdrant([])

    def _boom(**_kw):
        raise RuntimeError("qdrant no disponible")

    client.scroll = _boom
    sre_agent = _patch_env(monkeypatch, client, runbooks_dir)

    sre_agent.init_runbooks_qdrant()

    assert client.upserted == []


def test_real_runbooks_dir_has_the_new_playbooks():
    """Los playbooks del incidente están en el repo."""
    here = os.path.dirname(__file__)
    root = os.path.abspath(os.path.join(here, "..", "..", "..", ".."))
    rb = os.path.join(root, "runbooks")
    for f in ("job_pod_failed.md", "ollama_gpu_restart_storm.md", "notready_vs_crashed.md"):
        assert os.path.isfile(os.path.join(rb, f)), f"falta {f}"
