apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 05-backend-deployment.yaml
- 07-day-planner-cronjob.yaml
- 08-cosyvoice-deployment.yaml
- 09-piper-deployment.yaml
- 10-github-runner.yaml
images:
- name: registry.richardx.dev/amael-agentic-backend
  newTag: 1.10.2
